cmake_minimum_required(VERSION 3.19)
set (CMAKE_TOOLCHAIN_FILE "${CMAKE_CURRENT_LIST_DIR}/sdk/gcc-arm-eabi.cmake")
if(not "$ENV{HC32_CHIP_SERIES}" STREQUAL "")
    set(HC32_CHIP_SERIES $ENV{HC32_CHIP_SERIES})
endif()
if(not HC32_CHIP_SERIES)
    set(HC32_CHIP_SERIES "6")
endif()

if(HC32_CHIP_SERIES STREQUAL "4")
    set(HC32_LINKER_FILE_PATH "${CMAKE_CURRENT_LIST_DIR}/sdk/hc32l110x4.ld")
else()
    set(HC32_LINKER_FILE_PATH "${CMAKE_CURRENT_LIST_DIR}/sdk/hc32l110x6.ld")
endif()
include_directories("${CMAKE_CURRENT_LIST_DIR}/sdk/include")
link_directories("${CMAKE_CURRENT_LIST_DIR}/sdk/lib")

set(HC32_USE_LIBS "gcc" "hc32l110_ddl_core")

if(HC32_USE_DDL_GPIO)
    list (APPEND "hc32l110_ddl_gpio")
endif()
if(HC32_USE_DDL_BASIC_TIMERS)
    list (APPEND "hc32l110_ddl_basic_timers")
endif()
if(HC32_USE_DDL_DEBUG)
    list (APPEND "hc32l110_ddl_debug")
endif()
if(HC32_USE_DDL_I2C)
    list (APPEND "hc32l110_ddl_i2c")
endif()
if(HC32_USE_DDL_CLOCK_DYNAMIC)
    list (APPEND "hc32l110_ddl_clock_dynamic")
endif()
#- .\template\main.c  -lhc32l110_ddl_core -lhc32l110_ddl_gpio -lhc32l110_ddl_basic_timers -lgcc 
#-T .\template\hc32l110x6.ld -o blink.elf